# Generated by Django 5.2 on 2026-05-18 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_properties_rooms_alter_properties_rooms_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='properties',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='NearbyPlaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('category', models.CharField(choices=[('R', 'Restaurant'), ('G', 'Gym'), ('S', 'School'), ('H', 'Hospital'), ('SM', 'Supermarket'), ('P', 'Park')], max_length=2)),
                ('distance_meters', models.FloatField()),
                ('rating', models.FloatField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nearby_places', to='properties.properties')),
            ],
        ),
    ]
