# Generated by ChatGPT to add PropertyAlert model
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_favorites'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filters', models.JSONField(help_text='Filtros de busca salvos (mesmo formato da query string da API de busca)')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_notified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'property_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='propertyalert',
            index=models.Index(fields=['user', 'is_active'], name='property_al_user_is_active_idx'),
        ),
    ]