# Generated by Django 5.2 on 2026-05-19 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_propertyalert'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='propertyalert',
            new_name='property_al_user_id_2979e0_idx',
            old_name='property_al_user_is_active_idx',
        ),
    ]
